name: lavig-flow
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2025.11.4
  - ld_impl_linux-64=2.44
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.2
  - pthread-stubs=0.3
  - python=3.9.18
  - readline=8.3
  - sqlite=3.50.2
  - tk=8.6.15
  - tzdata=2025b
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - accelerate==1.10.1
      - anyio==4.11.0
      - certifi==2025.10.5
      - click==8.1.8
      - exceptiongroup==1.3.0
      - face-alignment==1.4.1
      - filelock==3.19.1
      - fsspec==2025.10.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.26.1
      - hydra-core==1.3.2
      - idna==3.11
      - imageio==2.37.2
      - importlib-metadata==8.7.0
      - jinja2==3.1.6
      - llvmlite==0.43.0
      - lmdb==1.7.5
      - markdown==3.9
      - markupsafe==3.0.3
      - moviepy==2.2.1
      - mpmath==1.3.0
      - networkx==3.2.1
      - numba==0.60.0
      - numpy==2.0.2
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - opencv-python==4.11.0.86
      - packaging==25.0
      - pandas==2.3.3
      - pillow==11.3.0
      - pip-chill==1.0.3
      - proglog==0.1.12
      - psutil==7.1.3
      - pyparsing==3.2.5
      - python-dotenv==1.2.1
      - pytz==2025.2
      - pyyaml==6.0.3
      - safetensors==0.6.2
      - setuptools==80.9.0
      - shellingham==1.5.4
      - smmap==5.0.2
      - sniffio==1.3.1
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboardx==2.6.4
      - tokenizers==0.19.1
      - torch==2.8.0
      - tqdm==4.67.1
      - transformers==4.44.2
      - triton==3.4.0
      - typer-slim==0.20.0
      - typing-extensions==4.15.0
      - zipp==3.23.0
