accelerator:
  gradient_accumulation_steps: 1
  mixed_precision: null
  split_batches: true
data:
  loader:
    batch_size: 4
    drop_last: true
    num_workers: 4
    persistent_workers: true
    pin_memory: true
    shuffle: true
  train:
    stats: /.../LAViG-FLOW/gas_saturation_vqvae/co2_data/training_dataset_gas_saturation/sg_train_min_max.pt
    target: /.../LAViG-FLOW/gas_saturation_vqvae/co2_data/train_sg_target.pt
loss:
  weights:
    codebook: 0.15
    commitment: 0.2
    lpips: 1.0
    recon: 1.0
lpips:
  enable: true
model:
  autoencoder:
    attns:
    - false
    - false
    - false
    codebook_size: 16384
    down_channels:
    - 256
    - 384
    - 512
    - 1024
    down_sample:
    - true
    - true
    - true
    mid_channels:
    - 1024
    - 1024
    norm_channels: 32
    num_down_layers: 2
    num_heads: 4
    num_mid_layers: 2
    num_up_layers: 2
    z_channels: 2
  im_channels: 1
optimizer:
  generator:
    betas:
    - 0.5
    - 0.999
    lr: 1.0e-05
output:
  checkpoints_dir: /.../LAViG-FLOW/gas_saturation_vqvae/trained_models/checkpoints
  loss_curve_filename: vqvae_loss_curves.png
  model_dir: /.../LAViG-FLOW/gas_saturation_vqvae/trained_models
  results_dir: /.../LAViG-FLOW/gas_saturation_vqvae/results
  save_config_copy: true
  summary_filename: vqvae_training_summary.txt
  tensorboard_subdir: tensorboard_logs
seed: 2025
training:
  auto_resume: true
  early_stopping_patience: null
  num_epochs: 60
  save_loss_curves: true
  tensorboard: true
